plugins:
	- jekyll-seo-tag

exclude: ["README.md"]
collections:
  pages:
    output: true
    permalink: /itvtbadboy/

layout: post
canonical_url: https://www.itvtbadboy.io.vn/
title: itvtbadboy
description: Itvtbadboy chuyên viên an ninh mạng parrot bảo mật công nghệ điện toán đám mây và lập trình tối ưu hiệu ứng tiềm năng từ khóa thời trang dịch vụ thương hiệu
logourl: https://www.itvtbadboy.io.vn/image/logoamp.png
logoalt: itvtbadboy
image: https://www.itvtbadboy.io.vn/image/itvtbadboy.jpg
locale: vi_VN

author:
	name: itvtbadboy
	url: https://github.com/itvtbadboy
webmaster_verifications:
	google: googlefebea4a6fd56bed1.html

social:
	name: itvtbadboy
	links:
		- https://www.pinterest.com/itvtbadboy/
		- https://www.youtube.com/@thuongmaibrvt
		- https://sg.linkedin.com/showcase/thuongmai
		- https://www.slideshare.net/MrBadBoy
		- https://www.facebook.com/groups/744087330470028
		- https://www.tiktok.com/@thuongmaibrvt
		- https://github.com/itvtbadboy/itvtbadboy.github.io
		- https://www.instagram.com/khuongitvtbadboy8383
		- https://soundcloud.com/khuongitvtbadboy
		- https://music.amazon.com/podcasts/6c25f7c0-aa43-4362-b83c-4b976b56df65/wiki-thuongmai-blog
		- https://news.google.com/publications/CAAqBwgKMNvklgsw3ouuAw?hl=vi-VN&gl=VN&ceid=VN:vi

twitter:
	username: badboyvt83
	card: summary
facebook:
	app_id: 110046038645905
	publisher: https://www.facebook.com/profile.php?id=100089607512698&locale=vi_VN
	admins: 100089607512698
